
GET http://localhost/api/food/archive/2023_1_23/2023_2_24


###

GET http://localhost/api/food/archive/248511


###


GET http://localhost/api/_versions


###


GET http://localhost/api/food HTTP/1.1
content-type: application/json


###

DELETE http://localhost/api/section/248511 HTTP/1.1
content-type: application/json


###



POST http://localhost/api/food/ HTTP/1.1
content-type: application/json

{
    "name": "Тест222",
    "section": "57599",
    "price": "50",
    "images":[],
    "info": ""
}

###

POST http://localhost/api/order/ HTTP/1.1
content-type: application/json

{
    "foodId": "1",
    "price": "50"
}

###




PUT http://localhost/api/order/1 HTTP/1.1
content-type: application/json

{
    "food": "food?",
    "foodId": "1",
    "price": "50"
}

###
###
{
    "food": [
        {"foodId":"1","price":"30"},
        {"foodId":"4","price":"40"}
    ]
}

###



POST http://localhost/api/section/ HTTP/1.1
content-type: application/json

{
    "name": "Прочее"
}

###




OPTIONS http://localhost/api/food/675531 HTTP/1.1
content-type: application/json

###