
GET http://localhost/api/food/archive/2023_1_23/2023_2_24


###

GET http://localhost/api/food/archive/248511


###


GET http://localhost/api/_versions


###


GET http://localhost/api/order HTTP/1.1
content-type: application/json


###

DELETE http://localhost/api/section/248511 HTTP/1.1
content-type: application/json


###



POST http://localhost/api/food/ HTTP/1.1
content-type: application/json

{
    "name": "Тест222",
    "section": "57599",
    "price": "50",
    "images":[],
    "info": ""
}

###

POST http://localhost/api/order/ HTTP/1.1
content-type: application/json

{
    "foodId": "1",
    "price": "50"
}

###




PUT http://localhost/api/order/1 HTTP/1.1
content-type: application/json

{
    "food": "food?",
    "foodId": "1",
    "price": "50"
}

###
###
{
    "food": [
        {"foodId":"1","price":"30"},
        {"foodId":"4","price":"40"}
    ]
}

###



POST http://localhost/api/section/ HTTP/1.1
content-type: application/json

{
    "name": "Прочее"
}

###




OPTIONS http://localhost/api/food/675531 HTTP/1.1
content-type: application/json

###
























PATCH https://wary-spectrum-mallet.glitch.me/users/0 HTTP/1.1
content-type: application/json

{
    "login": "Mather",
    "password": "I-love-c00kie$1",
    "token": "0_8938du3j98duu34jd"
}

###

DELETE https://wary-spectrum-mallet.glitch.me/users/2 HTTP/1.1


###








###

GET https://wary-spectrum-mallet.glitch.me/contacts HTTP/1.1


###

GET https://wary-spectrum-mallet.glitch.me/contacts?token=2_22222 HTTP/1.1



###

POST https://wary-spectrum-mallet.glitch.me/contacts HTTP/1.1
content-type: application/json

{"id":"","token":"1_11111","name":"цвцвцйв","fio":"уацуацуац","telephone":"+1 (111) 111-1111","email":"уцацуа"}

###

PATCH https://wary-spectrum-mallet.glitch.me/contacts/xDXRF8v HTTP/1.1
content-type: application/json

{
    "id": "xDXRF8v",
    "token": "1_11111",
    "name": "Qonwotejnka",
    "fio": "qqqqqqq",
    "telephone": "+79172333435",
    "email": "Qonwotejnka@mail.com"
}

###

GET https://wary-spectrum-mallet.glitch.me/contacts/xDXRF8v HTTP/1.1

###

DELETE https://wary-spectrum-mallet.glitch.me/contacts/11 HTTP/1.1